backend:
  name: git-gateway
  branch: netlify
publish_mode: editorial_workflow
media_folder: "source/_static"
public_folder: "_static"
collections:
  - name: "root"
    label: "Root"
    folder: "source/"
    create: false
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "drivetrains"
    label: "Drivetrains"
    folder: "source/docs/robot-design/drivetrains/"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
